name: Deploy Frontend to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  S3_BUCKET: mi-medicina-frontend
  CLOUDFRONT_DISTRIBUTION_ID: E1O1SEDX6RNH0W

jobs:
  deploy:
    name: Deploy to S3 and CloudFront
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build application
        run: npm run build
        env:
          VITE_API_URL: https://api.mi-medicina.com

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete --cache-control "public,max-age=31536000,immutable" --exclude "index.html"
          aws s3 cp dist/index.html s3://${{ env.S3_BUCKET }}/index.html --cache-control "public,max-age=0,must-revalidate"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deployment summary
        run: |
          echo "✅ Frontend deployed successfully!"
          echo "🌐 S3 Bucket: ${{ env.S3_BUCKET }}"
          echo "🚀 CloudFront invalidation created"
